# Generated by Django 2.0.3 on 2020-06-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
    ]
