# Generated by Django 2.1.7 on 2020-07-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_shape',
            field=models.CharField(choices=[('Full Plant', 'full plant'), ('Cutting', 'cutting'), ('Seed', 'seed')], default='Cutting', max_length=30),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('Indoor', 'indoor'), ('Outdoor', 'outdoor'), ('Indoor/Outdoor', 'indoor/outdoor')], default='Indoor', max_length=30),
        ),
    ]
