# Generated by Django 2.1.7 on 2020-06-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_exchange', '0002_remove_plant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_shape',
            field=models.CharField(default='Cutting', max_length=30),
        ),
    ]
