# Generated by Django 2.1.7 on 2020-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_exchange', '0003_auto_20200629_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_shape',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(max_length=30),
        ),
    ]
