# Generated by Django 2.1.7 on 2020-06-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_exchange', '0005_auto_20200629_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(default='This is a succulent', max_length=250),
        ),
    ]
